# Autodebugger Configuration
# Copy this file to config.yaml and customize as needed

# Log verbosity thresholds (only applies to INFO, DEBUG, TRACE levels)
# WARN and ERROR levels never trigger verbosity warnings - there's no such thing as "too many" errors/warnings!
verbosity:
  # Maximum logs allowed at each level before warning
  info_threshold: 50      # INFO level: general application flow
  debug_threshold: 100    # DEBUG level: detailed debugging info
  trace_threshold: 200    # TRACE level: very detailed trace logging

# Remove-debug command configuration
remove_debug:
  # Default paths to search when no paths are specified
  default_paths:
    - src
    - tests