# Autodebugger Configuration
# Copy this file to config.yaml and customize as needed

# Log verbosity thresholds
# These control when warnings are generated for excessive logging
verbosity:
  # Maximum logs allowed at each level before warning
  info_threshold: 50      # INFO level: general application flow
  debug_threshold: 100    # DEBUG level: detailed debugging info
  trace_threshold: 200    # TRACE level: very detailed trace logging
  warn_threshold: 25      # WARN level: warning messages
  error_threshold: 10     # ERROR level: error messages